# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 16:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='participation',
            name='answer',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('p', 'Pending')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='participation',
            name='is_necessary',
            field=models.BooleanField(default=False),
        ),
    ]
