# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170326_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('appointment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Appointment')),
                ('color', models.CharField(max_length=6)),
            ],
            bases=('backend.appointment',),
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='date_end',
            new_name='dtend',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='date_begin',
            new_name='dtstart',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='description',
            new_name='summary',
        ),
    ]
