# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20170301_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_begin',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_end',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
