# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_favorite_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='understudy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together=set([('actor', 'appointment')]),
        ),
    ]
