# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20170406_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='notes',
        ),
    ]
