# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20170414_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='bio',
            new_name='contact_notes',
        ),
        migrations.AddField(
            model_name='actor',
            name='education',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
