# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20170414_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='job',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='location',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='phone',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='skills',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='spare_time',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
