# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20170414_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='avatar',
            field=models.ImageField(default='avatars/noAvatar.jpg', upload_to='avatars/'),
        ),
    ]
