# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_actor_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='answer_relevant',
            field=models.BooleanField(default=True),
        ),
    ]
