# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20170419_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='avatar',
            field=models.ImageField(default='/avatars/default-avatar_0.jpg', upload_to='avatars/'),
        ),
    ]
